### ISSUE TITLE
Players should not be able to handshake themselves

### ISSUE THREAD

**Issue by vrde** [social-dist0rtion-protocol/toco2-contracts#11]
# Problem
Handshaking with yourself doesn't make much sense.

# Solution
Reject handshakes between two identical passport.

# Payment conditions
- contract update
- tests
- review

# Roles
- Gardener: @vrde / 5%
- Worker: ? / 80%
- Reviewer: ? / 15%

**Comment by johba37** [comment]
solved here: https://github.com/social-dist0rtion-protocol/planet-a-contracts/pull/12
