### ISSUE TITLE
update earth contract to use prisoners's dilemma

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/toco2-contracts#4]
## problem

linear game is boring.

## solution
introduce prisoners dilemma for trades with this matrix:

![IMG_20190717_104437](https://user-images.githubusercontent.com/659301/62218033-f56f4380-b3ab-11e9-8f33-f66ea168e3fe.jpg)

## payment conditions
- contracts and tests
- reviewer by owners

## roles
reviewer: @vrde 20%
gardner / worker @johannbarbie 80

**Comment by vrde** [comment]
The matrix is different:
![image](https://user-images.githubusercontent.com/134680/62638828-94f97c80-b93e-11e9-8631-325a054f02f0.png)

For the last test we used:
GOE => H: 10, M: 3, L: 1,
CO2 => H: 100, L: 1

**Comment by johba37** [comment]
@vrde updated

what i've actually implemented is this:

GOE => H: 10, M: 3, L: 1,
CO2 => H: 1000, L: 10

i think it makes more sense, just looking at the numbers (comments in tests)

**Comment by vrde** [comment]
First prisoner's dilemma™ handshakes using the new contract:
- collaborate (0.4Gt) collaborate: https://testnet.leapdao.org/explorer/tx/0x33e2e8f1451719759cbb42b0ff8d31ac7958d9cc15f27e5a2712ae89d408fc1e
- defect (20Gt) collaborate:  https://testnet.leapdao.org/explorer/tx0x2edbb83d6698115fcd8ec343c0b5bbeda45b759b1218f127223bf06df9235fc2
- collaborate (0.4Gt) defect: https://testnet.leapdao.org/explorer/tx/0x91beea6188074bc1b05afe9268e3550ab8f3ba7f349a79d3458475753e6b5504
- defect (20Gt) defect: https://testnet.leapdao.org/explorer/tx/0x3654033b8c77a5dcc25abfdf39dfa66ccc5a86cf20284606be7a54e9356e5f89
